stages:

  data_ingestion:
    cmd: python src/mlProject/pipeline/stage_01_data_ingestion.py
    deps:
      - src/mlProject/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/winequality-red.csv

  data_validation:
    cmd: python src/mlProject/pipeline/stage_02_data_validation.py
    deps:
      - src/mlProject/pipeline/stage_02_data_validation.py
      - config/config.yaml
      - schema.yaml
    outs:
      - artifacts/data_validation/status.txt  

  data_transformation:
    cmd: python src/mlProject/pipeline/stage_03_data_transformation.py
    deps:
      - src/mlProject/pipeline/stage_03_data_transformation.py
      - config/config.yaml
    outs:
      - artifacts/data_transformation/test.csv
      - artifacts/data_transformation/train.csv

  model_training:
    cmd: python src/mlProject/pipeline/stage_04_model_trainer.py
    deps:
      - src/mlProject/pipeline/stage_04_model_trainer.py
      - artifacts/data_transformation/train.csv
      - config/config.yaml
      - params.yaml
      - schema.yaml
    params:
      - ElasticNet.alpha
      - ElasticNet.l1_ratio
    outs:
      - artifacts/model_trainer/model.joblib

  model_evaluation:
    cmd: python src/mlProject/pipeline/stage_05_model_evaluation.py
    deps:
      - src/mlProject/pipeline/stage_05_model_evaluation.py
      - artifacts/model_trainer/model.joblib
      - artifacts/data_transformation/test.csv
      - config/config.yaml
      - params.yaml
      - schema.yaml
    params:
      - ElasticNet.alpha
      - ElasticNet.l1_ratio
    metrics:
      - artifacts/model_evaluation/metrics.json:
          cache: false