name: DockerHub CI/CD 

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Debug Secrets
      run: |
        echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
        echo "DOCKER_PASSWORD is set"
        if [[ -z "${{ secrets.DOCKER_USERNAME }}" ]]; then
          echo "DOCKER_USERNAME is empty. Ensure secrets are correctly set."
          exit 1
        fi

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/wine_quality_mlops:latest

    - name: Image digest
      run: echo ${{ steps.build-and-publish.outputs.digest }}